name = "ipfs add file"
services = [ "ipfs" ]
chains = [  ]
steps = [
  "cp $file ~/.eris/files/staging/",
  "docker exec $(docker ps | grep ipfs | cut -c 1-12) ipfs add -q /export/$file",
  "echo \"$name:$prev\" >> ~/.eris/files/list"
]

[environment]
HELLO="world"
WHEN="then"

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-actions"

[machine]
include = [ "docker" ]
requires = ""